// Auto-generated by backend/src/scripts/upload-industry-cover-images.js
// Do not edit manually. Re-run the script to update.

export const industryImages = {
  "agri-fmcg-beverage-pp": {
    name: "Agri&fmcg-beverage-pp",
    images: [
      { file: "image40.jpeg", url: "https://res.cloudinary.com/docyipoze/image/upload/v1756806258/cbm/industries/agri-fmcg-beverage-pp/gqgaqozpioawuhxmivcy.jpg", publicId: "cbm/industries/agri-fmcg-beverage-pp/gqgaqozpioawuhxmivcy" },
      { file: "image39.jpeg", url: "https://res.cloudinary.com/docyipoze/image/upload/v1756806260/cbm/industries/agri-fmcg-beverage-pp/pjpje3wuqlgee8selagi.jpg", publicId: "cbm/industries/agri-fmcg-beverage-pp/pjpje3wuqlgee8selagi" },
    ],
    coverImages: []
  },
  "cement-plants": {
    name: "Cement Plants",
    images: [
      { file: "image20.jpeg", url: "https://res.cloudinary.com/docyipoze/image/upload/v1756806261/cbm/industries/cement-plants/hi6mpuj7egh6x74j88ka.jpg", publicId: "cbm/industries/cement-plants/hi6mpuj7egh6x74j88ka" },
      { file: "image19.png", url: "https://res.cloudinary.com/docyipoze/image/upload/v1756806267/cbm/industries/cement-plants/gqlj3go1zzshvbogghcf.jpg", publicId: "cbm/industries/cement-plants/gqlj3go1zzshvbogghcf" },
    ],
    coverImages: [
      { file: "image2.jpeg", url: "https://res.cloudinary.com/docyipoze/image/upload/v1757234430/cbm/industries/cement-plants/covers/jbknna7jatilxg2zk6vl.jpg", publicId: "cbm/industries/cement-plants/covers/jbknna7jatilxg2zk6vl" },
    ]
  },
  "fertilizer-plants": {
    name: "Fertilizer Plants",
    images: [
      { file: "image28.jpeg", url: "https://res.cloudinary.com/docyipoze/image/upload/v1756806269/cbm/industries/fertilizer-plants/zsox7hqhnxpe4jwczvnt.jpg", publicId: "cbm/industries/fertilizer-plants/zsox7hqhnxpe4jwczvnt" },
      { file: "image27.jpeg", url: "https://res.cloudinary.com/docyipoze/image/upload/v1756806272/cbm/industries/fertilizer-plants/d98lxpgtqsnkwjtufnkq.jpg", publicId: "cbm/industries/fertilizer-plants/d98lxpgtqsnkwjtufnkq" },
    ],
    coverImages: [
      { file: "image6.jpeg", url: "https://res.cloudinary.com/docyipoze/image/upload/v1757234434/cbm/industries/fertilizer-plants/covers/da1tr4rvdpzkrtwt852u.jpg", publicId: "cbm/industries/fertilizer-plants/covers/da1tr4rvdpzkrtwt852u" },
    ]
  },
  "fso-fpso": {
    name: "FSO-FPSO",
    images: [
      { file: "image32.jpeg", url: "https://res.cloudinary.com/docyipoze/image/upload/v1756806273/cbm/industries/fso-fpso/qmbnidojair3anpjvkxw.jpg", publicId: "cbm/industries/fso-fpso/qmbnidojair3anpjvkxw" },
      { file: "image31.png", url: "https://res.cloudinary.com/docyipoze/image/upload/v1756806276/cbm/industries/fso-fpso/e4aj5mlwuf4xhnme1hhl.jpg", publicId: "cbm/industries/fso-fpso/e4aj5mlwuf4xhnme1hhl" },
    ],
    coverImages: [
      { file: "image8.jpeg", url: "https://res.cloudinary.com/docyipoze/image/upload/v1757234436/cbm/industries/fso-fpso/covers/pswfbcy62c6qoazbyx8m.jpg", publicId: "cbm/industries/fso-fpso/covers/pswfbcy62c6qoazbyx8m" },
    ]
  },
  "heavy-automotive": {
    name: "Heavy Automotive",
    images: [
      { file: "image44.png", url: "https://res.cloudinary.com/docyipoze/image/upload/v1756806278/cbm/industries/heavy-automotive/reod98a2nt4ymwrubs1i.jpg", publicId: "cbm/industries/heavy-automotive/reod98a2nt4ymwrubs1i" },
      { file: "image43.jpeg", url: "https://res.cloudinary.com/docyipoze/image/upload/v1756806279/cbm/industries/heavy-automotive/biim27jwt1l7u1sd3vlg.jpg", publicId: "cbm/industries/heavy-automotive/biim27jwt1l7u1sd3vlg" },
    ],
    coverImages: [
      { file: "image14.jpeg", url: "https://res.cloudinary.com/docyipoze/image/upload/v1757234438/cbm/industries/heavy-automotive/covers/x0e0oq4jchh32wmtx8t4.jpg", publicId: "cbm/industries/heavy-automotive/covers/x0e0oq4jchh32wmtx8t4" },
    ]
  },
  "industrial-manufacturing-processing": {
    name: "Industrial Manufacturing & Processing",
    images: [
      { file: "image42.jpeg", url: "https://res.cloudinary.com/docyipoze/image/upload/v1756806282/cbm/industries/industrial-manufacturing-processing/t1ymkvpv0eusgtim5nxx.jpg", publicId: "cbm/industries/industrial-manufacturing-processing/t1ymkvpv0eusgtim5nxx" },
      { file: "image41.jpeg", url: "https://res.cloudinary.com/docyipoze/image/upload/v1756806283/cbm/industries/industrial-manufacturing-processing/tsa0ucda6jezxste2nsz.jpg", publicId: "cbm/industries/industrial-manufacturing-processing/tsa0ucda6jezxste2nsz" },
    ],
    coverImages: [
      { file: "image13.png", url: "https://res.cloudinary.com/docyipoze/image/upload/v1757234447/cbm/industries/industrial-manufacturing-processing/covers/xl1f85ckfdnrfqgekb9a.jpg", publicId: "cbm/industries/industrial-manufacturing-processing/covers/xl1f85ckfdnrfqgekb9a" },
    ]
  },
  "mining-metals-plants-refineries": {
    name: "Mining & Metals Plants & Refineries",
    images: [
      { file: "image18.jpeg", url: "https://res.cloudinary.com/docyipoze/image/upload/v1756806285/cbm/industries/mining-metals-plants-refineries/vcba4hypoyw0vxdl2ek9.jpg", publicId: "cbm/industries/mining-metals-plants-refineries/vcba4hypoyw0vxdl2ek9" },
      { file: "image17.jpeg", url: "https://res.cloudinary.com/docyipoze/image/upload/v1756806286/cbm/industries/mining-metals-plants-refineries/z67flz0qw2a7u6vdh7kl.jpg", publicId: "cbm/industries/mining-metals-plants-refineries/z67flz0qw2a7u6vdh7kl" },
    ],
    coverImages: [
      { file: "image1.jpeg", url: "https://res.cloudinary.com/docyipoze/image/upload/v1757234449/cbm/industries/mining-metals/covers/pz8meieccbqqnzxfndn3.jpg", publicId: "cbm/industries/mining-metals/covers/pz8meieccbqqnzxfndn3" },
    ]
  },
  "oil-gas": {
    name: "Oil & Gas",
    images: [
      { file: "image24.jpeg", url: "https://res.cloudinary.com/docyipoze/image/upload/v1756806287/cbm/industries/oil-gas/ltwj3255n2eobaaundpa.jpg", publicId: "cbm/industries/oil-gas/ltwj3255n2eobaaundpa" },
      { file: "image23.jpeg", url: "https://res.cloudinary.com/docyipoze/image/upload/v1756806289/cbm/industries/oil-gas/zh9xmyfzcwq3arihfkpz.jpg", publicId: "cbm/industries/oil-gas/zh9xmyfzcwq3arihfkpz" },
    ],
    coverImages: [
      { file: "image4.jpeg", url: "https://res.cloudinary.com/docyipoze/image/upload/v1757234451/cbm/industries/oil-gas/covers/iixgypd5s9cqt1nwp7pr.jpg", publicId: "cbm/industries/oil-gas/covers/iixgypd5s9cqt1nwp7pr" },
    ]
  },
  "paper-pulp-man-plants": {
    name: "paper&pulp-man-plants",
    images: [
      { file: "image38.jpeg", url: "https://res.cloudinary.com/docyipoze/image/upload/v1756806290/cbm/industries/paper-pulp-man-plants/nttmttuuqmnuo2kpwih7.jpg", publicId: "cbm/industries/paper-pulp-man-plants/nttmttuuqmnuo2kpwih7" },
      { file: "image37.jpeg", url: "https://res.cloudinary.com/docyipoze/image/upload/v1756806292/cbm/industries/paper-pulp-man-plants/s9czwhwykxxbijsldvlg.jpg", publicId: "cbm/industries/paper-pulp-man-plants/s9czwhwykxxbijsldvlg" },
    ],
    coverImages: []
  },
  "petrochemicals-p-r": {
    name: "petrochemicals-p-r",
    images: [
      { file: "image26.jpeg", url: "https://res.cloudinary.com/docyipoze/image/upload/v1756806294/cbm/industries/petrochemicals-p-r/apt0rvrtlpwuahj7h3ny.jpg", publicId: "cbm/industries/petrochemicals-p-r/apt0rvrtlpwuahj7h3ny" },
      { file: "image25.jpeg", url: "https://res.cloudinary.com/docyipoze/image/upload/v1756806295/cbm/industries/petrochemicals-p-r/vaamwjvttbwdaofgs0g5.jpg", publicId: "cbm/industries/petrochemicals-p-r/vaamwjvttbwdaofgs0g5" },
    ],
    coverImages: []
  },
  "pharmaceutical-plants": {
    name: "pharmaceutical-plants",
    images: [
      { file: "image30.jpeg", url: "https://res.cloudinary.com/docyipoze/image/upload/v1756806297/cbm/industries/pharmaceutical-plants/wjyf4ujxsft1zcsz5hb6.jpg", publicId: "cbm/industries/pharmaceutical-plants/wjyf4ujxsft1zcsz5hb6" },
      { file: "image29.jpeg", url: "https://res.cloudinary.com/docyipoze/image/upload/v1756806298/cbm/industries/pharmaceutical-plants/cvkyx6e8xyimv1olgci4.jpg", publicId: "cbm/industries/pharmaceutical-plants/cvkyx6e8xyimv1olgci4" },
    ],
    coverImages: [
      { file: "image7.jpeg", url: "https://res.cloudinary.com/docyipoze/image/upload/v1757234455/cbm/industries/pharmaceutical-plants/covers/clxyaaxrkdtzz61zbl96.jpg", publicId: "cbm/industries/pharmaceutical-plants/covers/clxyaaxrkdtzz61zbl96" },
    ]
  },
  "power-plants-utilities": {
    name: "power-plants-utilities",
    images: [
      { file: "image34.jpeg", url: "https://res.cloudinary.com/docyipoze/image/upload/v1756806300/cbm/industries/power-plants-utilities/chhxxywucn24owkzzike.jpg", publicId: "cbm/industries/power-plants-utilities/chhxxywucn24owkzzike" },
      { file: "image33.jpeg", url: "https://res.cloudinary.com/docyipoze/image/upload/v1756806303/cbm/industries/power-plants-utilities/xauxupcp5snobub0knn7.jpg", publicId: "cbm/industries/power-plants-utilities/xauxupcp5snobub0knn7" },
    ],
    coverImages: []
  },
  "railways": {
    name: "railways",
    images: [
      { file: "image46.jpeg", url: "https://res.cloudinary.com/docyipoze/image/upload/v1756806305/cbm/industries/railways/y5effkf3tiqyoi7i4t4t.jpg", publicId: "cbm/industries/railways/y5effkf3tiqyoi7i4t4t" },
      { file: "image45.jpeg", url: "https://res.cloudinary.com/docyipoze/image/upload/v1756806307/cbm/industries/railways/dtmqkyqqyxyxjnrz87tw.jpg", publicId: "cbm/industries/railways/dtmqkyqqyxyxjnrz87tw" },
    ],
    coverImages: []
  },
  "roads-and-bridges": {
    name: "Roads and Bridges",
    images: [
      { file: "image48.jpeg", url: "https://res.cloudinary.com/docyipoze/image/upload/v1756806309/cbm/industries/roads-and-bridges/ekyfjdazclkffckjfj1b.jpg", publicId: "cbm/industries/roads-and-bridges/ekyfjdazclkffckjfj1b" },
      { file: "image47.jpeg", url: "https://res.cloudinary.com/docyipoze/image/upload/v1756806310/cbm/industries/roads-and-bridges/iduaihsb1nboubrunqdv.jpg", publicId: "cbm/industries/roads-and-bridges/iduaihsb1nboubrunqdv" },
    ],
    coverImages: [
      { file: "image16.png", url: "https://res.cloudinary.com/docyipoze/image/upload/v1757234463/cbm/industries/roads-and-bridges/covers/kyovm9nqqarebe1v1y6y.jpg", publicId: "cbm/industries/roads-and-bridges/covers/kyovm9nqqarebe1v1y6y" },
    ]
  },
  "steelplants": {
    name: "steelplants",
    images: [
      { file: "image22.jpeg", url: "https://res.cloudinary.com/docyipoze/image/upload/v1756806311/cbm/industries/steelplants/z1mkjachceuoqvjiooaf.jpg", publicId: "cbm/industries/steelplants/z1mkjachceuoqvjiooaf" },
      { file: "image21.jpeg", url: "https://res.cloudinary.com/docyipoze/image/upload/v1756806312/cbm/industries/steelplants/oaqecwxm189dfp1z5vzu.jpg", publicId: "cbm/industries/steelplants/oaqecwxm189dfp1z5vzu" },
    ],
    coverImages: []
  },
  "sugarplants": {
    name: "sugarplants",
    images: [
      { file: "image36.jpeg", url: "https://res.cloudinary.com/docyipoze/image/upload/v1756806313/cbm/industries/sugarplants/woncvgnzqvxpqtw5q74u.jpg", publicId: "cbm/industries/sugarplants/woncvgnzqvxpqtw5q74u" },
      { file: "image35.jpeg", url: "https://res.cloudinary.com/docyipoze/image/upload/v1756806315/cbm/industries/sugarplants/gks7yyjocmgqy3migivq.jpg", publicId: "cbm/industries/sugarplants/gks7yyjocmgqy3migivq" },
    ],
    coverImages: []
  },
  "aerospace-defense": {
    name: "Aerospace & Defense",
    images: [
    ],
    coverImages: []
  },
  "automotive": {
    name: "Automotive",
    images: [
    ],
    coverImages: []
  },
  "construction-infrastructure": {
    name: "Construction & Infrastructure",
    images: [
    ],
    coverImages: []
  },
  "energy-utilities": {
    name: "Energy & Utilities",
    images: [
    ],
    coverImages: []
  },
  "food-agriculture": {
    name: "Food & Agriculture",
    images: [
    ],
    coverImages: []
  },
  "healthcare-medical-devices": {
    name: "Healthcare & Medical Devices",
    images: [
    ],
    coverImages: []
  },
  "manufacturing": {
    name: "Manufacturing",
    images: [
    ],
    coverImages: []
  },
  "technology-electronics": {
    name: "Technology & Electronics",
    images: [
    ],
    coverImages: []
  },
  "agri-fmcg-beverage-processing-plants": {
    name: "Agri & FMCG Beverage Processing Plants",
    images: [
    ],
    coverImages: [
      { file: "image12.jpeg", url: "https://res.cloudinary.com/docyipoze/image/upload/v1757234426/cbm/industries/agri-fmcg-beverage-processing-plants/covers/kiyundu8oez28oxl9glm.jpg", publicId: "cbm/industries/agri-fmcg-beverage-processing-plants/covers/kiyundu8oez28oxl9glm" },
    ]
  },
  "paper-pulp-manufacturing-plants": {
    name: "Paper & Pulp Manufacturing Plants",
    images: [
    ],
    coverImages: [
      { file: "image11.jpeg", url: "https://res.cloudinary.com/docyipoze/image/upload/v1757234453/cbm/industries/paper-pulp-manufacturing-plants/covers/ajgkig6ryfdvwtkllxb2.jpg", publicId: "cbm/industries/paper-pulp-manufacturing-plants/covers/ajgkig6ryfdvwtkllxb2" },
    ]
  },
  "petrochemical-plants-refineries": {
    name: "Petrochemical Plants & Refineries",
    images: [
    ],
    coverImages: [
      { file: "image5.jpeg", url: "https://res.cloudinary.com/docyipoze/image/upload/v1757234454/cbm/industries/petrochemical-plants-refineries/covers/hplktuzc0lzgc7vo25g8.jpg", publicId: "cbm/industries/petrochemical-plants-refineries/covers/hplktuzc0lzgc7vo25g8" },
    ]
  },
  "power-plants-and-utilities": {
    name: "Power Plants and Utilities",
    images: [
    ],
    coverImages: [
      { file: "image9.jpeg", url: "https://res.cloudinary.com/docyipoze/image/upload/v1757234457/cbm/industries/power-plants-and-utilities/covers/slu7viaze6u0nphhis7h.jpg", publicId: "cbm/industries/power-plants-and-utilities/covers/slu7viaze6u0nphhis7h" },
    ]
  },
  "railway": {
    name: "Railway",
    images: [
    ],
    coverImages: [
      { file: "image15.png", url: "https://res.cloudinary.com/docyipoze/image/upload/v1757234460/cbm/industries/railway/covers/ktsvzpzywuoywn8fysuu.jpg", publicId: "cbm/industries/railway/covers/ktsvzpzywuoywn8fysuu" },
    ]
  },
  "steel-plants": {
    name: "Steel Plants",
    images: [
    ],
    coverImages: [
      { file: "image3.jpeg", url: "https://res.cloudinary.com/docyipoze/image/upload/v1757234464/cbm/industries/steel-plants/covers/mxlmwswwhkzxxcf3bibv.jpg", publicId: "cbm/industries/steel-plants/covers/mxlmwswwhkzxxcf3bibv" },
    ]
  },
  "sugar-plants": {
    name: "Sugar Plants",
    images: [
    ],
    coverImages: [
      { file: "image10.jpeg", url: "https://res.cloudinary.com/docyipoze/image/upload/v1757234466/cbm/industries/sugar-plants/covers/vowyrtefp8uyros2d3w7.jpg", publicId: "cbm/industries/sugar-plants/covers/vowyrtefp8uyros2d3w7" },
    ]
  },
};

export default industryImages;
